// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalutVaga.Models
{
    public partial class CanalCompra
    {
        public CanalCompra()
        {
            NotaFiscal = new HashSet<NotaFiscal>();
        }

        [Key]
        [Column("id_canalcompra")]
        public int IdCanalcompra { get; set; }
        [Column("des_canalcompra")]
        [StringLength(300)]
        public string DesCanalcompra { get; set; }
        [Column("dt_inclusão", TypeName = "datetime")]
        public DateTime? DtInclusão { get; set; }
        [Column("dt_alteracao", TypeName = "datetime")]
        public DateTime? DtAlteracao { get; set; }
        [Column("flg_situacao")]
        public bool? FlgSituacao { get; set; }

        [InverseProperty("CodCanalcompraNavigation")]
        public virtual ICollection<NotaFiscal> NotaFiscal { get; set; }
    }
}