// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SalutVaga.Models
{
    public partial class DB_SALUTContext : DbContext
    {
        public DB_SALUTContext()
        {
        }

        public DB_SALUTContext(DbContextOptions<DB_SALUTContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CanalCompra> CanalCompra { get; set; }
        public virtual DbSet<NotaFiscal> NotaFiscal { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CanalCompra>(entity =>
            {
                entity.HasKey(e => e.IdCanalcompra)
                    .HasName("PK__CanalCom__94EBE0CA1337D272");

                entity.Property(e => e.DesCanalcompra).IsUnicode(false);
            });

            modelBuilder.Entity<NotaFiscal>(entity =>
            {
                entity.HasKey(e => e.IdNotafiscal)
                    .HasName("PK__NotaFisc__265711AF0203004B");

                entity.Property(e => e.DesCaminhoAnexo).IsUnicode(false);

                entity.Property(e => e.DesCnpj).IsUnicode(false);

                entity.Property(e => e.DesNotafiscal).IsUnicode(false);

                entity.HasOne(d => d.CodCanalcompraNavigation)
                    .WithMany(p => p.NotaFiscal)
                    .HasForeignKey(d => d.CodCanalcompra)
                    .HasConstraintName("FK__NotaFisca__cod_c__76969D2E");

                entity.HasOne(d => d.CodProdutoNavigation)
                    .WithMany(p => p.NotaFiscal)
                    .HasForeignKey(d => d.CodProduto)
                    .HasConstraintName("FK__NotaFisca__cod_p__778AC167");
            });

            modelBuilder.Entity<Produto>(entity =>
            {
                entity.HasKey(e => e.IdProduto)
                    .HasName("PK__Produto__BA38A6B8D2EB096E");

                entity.Property(e => e.DesProduto).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}