// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalutVaga.Models
{
    public partial class NotaFiscal
    {
        [Key]
        [Column("id_notafiscal")]
        public int IdNotafiscal { get; set; }
        [Column("des_cnpj")]
        [StringLength(50)]
        public string DesCnpj { get; set; }
        [Column("cod_canalcompra")]
        public int? CodCanalcompra { get; set; }
        [Column("dt_compra", TypeName = "datetime")]
        public DateTime? DtCompra { get; set; }
        [Column("des_notafiscal")]
        [StringLength(100)]
        public string DesNotafiscal { get; set; }
        [Column("quantidade")]
        public int? Quantidade { get; set; }
        [Column("des_caminhoAnexo")]
        [StringLength(5000)]
        public string DesCaminhoAnexo { get; set; }
        [Column("cod_produto")]
        public int? CodProduto { get; set; }
        [Column("dt_inclusão", TypeName = "datetime")]
        public DateTime? DtInclusão { get; set; }
        [Column("dt_alteracao", TypeName = "datetime")]
        public DateTime? DtAlteracao { get; set; }
        [Column("flg_situacao")]
        public bool? FlgSituacao { get; set; }

        [ForeignKey(nameof(CodCanalcompra))]
        [InverseProperty(nameof(CanalCompra.NotaFiscal))]
        public virtual CanalCompra CodCanalcompraNavigation { get; set; }
        [ForeignKey(nameof(CodProduto))]
        [InverseProperty(nameof(Produto.NotaFiscal))]
        public virtual Produto CodProdutoNavigation { get; set; }
    }
}