// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalutVaga.Models
{
    public partial class Produto
    {
        public Produto()
        {
            NotaFiscal = new HashSet<NotaFiscal>();
        }

        [Key]
        [Column("id_produto")]
        public int IdProduto { get; set; }
        [Column("des_produto")]
        [StringLength(200)]
        public string DesProduto { get; set; }
        [Column("dt_inclusão", TypeName = "datetime")]
        public DateTime? DtInclusão { get; set; }
        [Column("dt_alteracao", TypeName = "datetime")]
        public DateTime? DtAlteracao { get; set; }
        [Column("flg_situacao")]
        public bool? FlgSituacao { get; set; }

        [InverseProperty("CodProdutoNavigation")]
        public virtual ICollection<NotaFiscal> NotaFiscal { get; set; }
    }
}